fields: ~
#    description:
#        type: text
#        dynamic: true
#        options:
#            limit: 1
#            # ...
#        widget:
#            type: text.formatted
#            options:
#                default: 'Default Text'

search:
    handler: Gravity\CmsBundle\Search\Handler\TaxonomyHandler

display:
  handler: node_list
  options:
    template: 'AndyThorneSandboxBundle:Node:list-by-tag.html.twig'
    node_types:
        'AndyThorne\SandboxBundle\Entity\BlogPost': tags

routing:
    path: /tag/{name}
    extendable: true
