services:
  gravity_cms.field.text:
    class: Gravity\CmsBundle\Field\Type\Text\TextField
    tags:
      - { name: gravity_cms.field }

  # Formatted Widget
  gravity_cms.field.text.widget.formatted:
    class: Gravity\CmsBundle\Field\Type\Text\Widget\Formatted\FormattedWidget
    tags:
      - { name: gravity_cms.field.widget }

  gravity_cms.field.text.widget.formatted.form:
    class: Gravity\CmsBundle\Field\Type\Text\Widget\Formatted\FormattedWidgetForm
    tags:
      - { name: form.type, alias: gravity_field_text_widget }

  # Unformatted Widget
  gravity_cms.field.text.widget.unformatted:
    class: Gravity\CmsBundle\Field\Type\Text\Widget\UnFormatted\UnFormattedWidget
    tags:
      - { name: gravity_cms.field.widget }

  gravity_cms.field.text.display.text:
    class: Gravity\CmsBundle\Field\Type\Text\Display\Formatted\FormattedDisplay
    tags:
      - { name: gravity_cms.field.display }

  gravity_cms.field.text.display.url:
    class: Gravity\CmsBundle\Field\Type\Text\Display\Url\UrlDisplay
    tags:
      - { name: gravity_cms.field.display }
