
services:
  gravity_cms.field.boolean:
    class: Gravity\CmsBundle\Field\Type\Boolean\BooleanField
    tags:
      - { name: gravity_cms.field }

  gravity_cms.field.boolean.widget.checkbox:
    class: Gravity\CmsBundle\Field\Type\Boolean\Widget\Checkbox\CheckboxWidget
    tags:
      - { name: gravity_cms.field.widget }

#  gravity_cms.field.boolean.widget.select:
#    class: Gravity\CmsBundle\Field\Type\Choice\Widget\Select\SelectWidget
#    tags:
#      - { name: gravity_cms.field.widget }

  gravity_cms.field.boolean.display.boolean:
    class: Gravity\CmsBundle\Field\Type\Boolean\Display\BooleanDisplay
    tags:
      - { name: gravity_cms.field.display }
