sonata_admin:
    templates:
        # other configuration options
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig

sonata_block:
    blocks:
        sonata.admin.block.search_result:
        #contexts: [admin]
