framework:
    templating:
        loaders:
          - templating.loader.filesystem
          - templating.loader.theme_loader

sonata_admin:
    templates:
        # default global templates
        layout:  GravityAdminBundle::gravity_layout.html.twig

    options:
        use_icheck: false

    assets:
        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
        
            - bundles/sonatacore/vendor/moment/min/moment.min.js
        
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
        
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
        
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
        
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
        
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
        
            - bundles/sonataadmin/vendor/select2/select2.min.js
        
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

            - bundles/gravitycms/js/form/fields.js
        stylesheets: []

cmf_routing:
  chain:
    routers_by_id:
      cmf_routing.dynamic_router: 300
      router.default: 200
  dynamic:
#    enabled: true
#    route_provider_service_id: gravity_cms.routing.cms_route_provider
    route_collection_limit: false
    persistence:
      orm: ~

assetic:
    bundles:
      - GravityAdminBundle

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
