twig:
    form_themes:
      - GravityCmsBundle:Form:fields.html.twig

sonata_admin:
    title:      Gravity

#    dashboard:
#        groups:
#            gravity_cms.admin.group.content:
#                label:           gravity_cms_content
#                label_catalogue: GravityCmsBundle
#                icon:            '<i class="fa fa-th"></i>'
#                items: []

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.formatter.block.formatter:

gravity_cms:
    site:
        name: GravityCMS Demo
    user_entity: AndyThorne\SandboxBundle\Entity\User
    node_types:
        page:
            class: AndyThorne\SandboxBundle\Entity\Page
            admin:
              class: Gravity\CmsBundle\Admin\NodeAdmin
              category: Content
              label: Page

        blog_post:
            class: AndyThorne\SandboxBundle\Entity\BlogPost
            admin:
              class: Gravity\CmsBundle\Admin\NodeAdmin
              category: Content
              label: Blog Post
        tag:
            class: AndyThorne\SandboxBundle\Entity\Tag
            admin:
              class: Gravity\TagBundle\Admin\TagAdmin
              category: Taxonomy
              label: Tag
        category:
            class: AndyThorne\SandboxBundle\Entity\Category
            admin:
              class: Gravity\TagBundle\Admin\TagAdmin
              category: Taxonomy
              label: Categoty

ivory_ck_editor:
    default_config: default
    configs:
        default:
            extraPlugins: 'divarea,wordcount,filebrowser'
            #removeButtons: 'About,Maximize'
            #removePlugins: 'elementspath'
            #scayt_autoStartup: true
            allowedContent: true
    plugins:
        divarea:
            path: /bundles/gravitycms/vendor/ckeditor-plugins/divarea/
            filename: plugin.js
        wordcount:
            path: /bundles/gravitycms/vendor/ckeditor-plugins/wordcount/
            filename: plugin.js