andy_thorne_blog_roll:
    path: /blog
    defaults:
        _controller: "GravityCmsBundle:NodeList:list"
        _entity: AndyThorne\SandboxBundle\Entity\BlogPost
        _list_template: "AndyThorneSandboxBundle:Node:list.html.twig"
        _title: "Articles"